### ISSUE TITLE
It stopped showing data again?

### ISSUE THREAD

**Issue by dijazolagit** [RBND-studio/fig-stats#11]
Hey guys, I just saw that the last day with the date was Sep 26, 2024, any update so far? Thanks.

**Comment by OPesicka** [comment]
@dijazolagit can you share URL of the plugin/widget you see this on? I see the latest data 👇  Maybe try refreshing on the plugin/widget page, the old data could be cached

![image](https://github.com/user-attachments/assets/5160554b-f55b-4b17-8b92-b9be359e61cd)

**Comment by dijazolagit** [comment]
All good now, thanks!
