### ISSUE TITLE
What is the diff of unique runs and installs?

### ISSUE THREAD

**Issue by shijiatongxue** [RBND-studio/fig-stats#2]
Hi there,

I am confusing about unique runs and installs. What is the diff between this.

![image](https://user-images.githubusercontent.com/26477537/219823359-3ab05441-b35a-4487-a358-b913bc157f5c.png)

In Figma community page, it only has `try it out`. Why fig-stats define it as unique run?

![image](https://user-images.githubusercontent.com/26477537/219823378-845dd729-1300-44ad-81ea-a69ab050734d.png)

Thanks!

**Comment by OPesicka** [comment]
Hey @shijiatongxue, sorry for the delay. We are getting these data from Figma API and that is how they call them. As far as I understand it:

- Unique runs - how many unique users ran the plugin (run = start/try out)
- Installs (now called Saves)- you can "save" a plugin to access it quicker in Figma. That's what installs refer to. Before June 2022 installing was the only way of using plugins.

Hope this clears it up.

**Comment by shijiatongxue** [comment]
Thanks a lot.



---- Replied Message ----
| From | Ondřej ***@***.***> |
| Date | 08/06/2023 23:42 |
| To | ***@***.***> |
| Cc | Shi ***@***.***>***@***.***> |
| Subject | Re: [RBND-studio/fig-stats] What is the diff of unique runs and installs? (Issue #2) |

Hey @shijiatongxue, sorry for the delay. We are getting these data from Figma API and that is how they call them. As far as I understand it:

Unique runs - how many unique users ran the plugin (run = start/try out)
Installs (now called Saves)- you can "save" a plugin to access it quicker in Figma. That's what installs refer to. Before June 2022 installing was the only way of using plugins.

Hope this clears it up.
