### ISSUE TITLE
Missing data for June 30th & July 9th

### ISSUE THREAD

**Issue by inerds** [RBND-studio/fig-stats#4]
Data is missing for the following two dates
June 30, 2023 & July 9, 2023

<img width="394" alt="Screenshot 2023-07-12 at 09 28 50" src="https://github.com/RBND-studio/fig-stats/assets/140153/478c706c-b7e9-4894-9b07-3a9630bcfb75">

**Comment by OPesicka** [comment]
Thanks for the notice @inerds! We had a random outage and noticed it too late to recover the data 😞
