### ISSUE TITLE
Bug displaying 29th day of month

### ISSUE THREAD

**Issue by brainshift-design** [RBND-studio/fig-stats#7]
Could it be a time zone issue because of the daylight savings switch?

![image](https://github.com/RBND-studio/fig-stats/assets/136026582/c3eb9312-df2f-42a7-8ebf-df9688814c60)

**Comment by VojtechVidra** [comment]
Thanks for the report! You're probably right, the JavaScript Date function was behaving a bit weird. Now it's fixed 🎉
