### ISSUE TITLE
Spike in the number of users at the beginning of the year

### ISSUE THREAD

**Issue by Antonytm** [RBND-studio/fig-stats#8]
It looks like there is some issue with the end/beginning of the year.
All plugins have spikes in the number of users.

![image](https://github.com/RBND-studio/fig-stats/assets/647813/60fa6514-6a92-4f58-b063-a879c15dd457)

**Comment by OPesicka** [comment]
Hey, thanks for reporting 🙌  It seems we skipped some days for these plugins @VojtechVidra can you check it out? 

For example, I can see that for this plugin https://fig-stats.com/plugins/845838702454033341 we are missing December 30, 31. But the plugin is in the raw data for these days.

**Comment by VojtechVidra** [comment]
We had an issue with collecting the data. Now the data is backfilled 🎉
