### ISSUE TITLE
Many plugins have very low amount of views in the December

### ISSUE THREAD

**Issue by Antonytm** [RBND-studio/fig-stats#9]
It looks like something is wrong with the number of views for December
![image](https://github.com/RBND-studio/fig-stats/assets/647813/f4bff90a-970b-438b-aeb3-dab5f1baaaef)

A similar picture is for other plugins as well.

**Comment by OPesicka** [comment]
Thanks for reporting. @VojtechVidra any ideas?

**Comment by OPesicka** [comment]
This looks like a Figma issue. On Nov 30, 2023, they released "New Community pages layout" which probably messed up their views data tracking. We can't do anything about this since we consume what Figma tells us daily.

Added a note about this to the charts to clarify what happened.
